doctrine:
  dbal:
    connections:
      default:
        driver: 'pdo_pgsql'
        server_version: '11'
        charset: UTF8
        host: '%db.postgresql.host%'
        port: '%db.postgresql.port%'
        dbname: '%db.postgresql.dbname%'
        user: '%db.postgresql.user%'
        password: '%db.postgresql.password%'
        mapping_types:
          enum: string
    types:
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

#doctrine:
#  dbal:
#    connections:
#      default:
#        # DATABASE_URL would be of "mysql://db_user:db_password@127.0.0.1:3306/db_name"
#        url: '%env(resolve:DATABASE_URL)%'
#        wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection'
#        options:
#          x_reconnect_attempts: 3
