services:
  _defaults:
    public: true

  # Dto
  game.proxx.application.dto.factory:
    class: Micro\Game\Proxx\Application\Dto\Factory\ProxxDtoFactory

  # Default Command handlers
  game.proxx.application.command_handler.board.create:
    class: Micro\Game\Proxx\Application\CommandHandler\CreateBoardHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
      - '@game.proxx.domain.factory.value-object'
      - '@game.proxx.domain.factory.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\CreateBoardCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.calculate-black-holes-around:
    class: Micro\Game\Proxx\Application\CommandHandler\CalculateBlackHolesAroundHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\CalculateBlackHolesAroundCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.place-black-holes-handler:
    class: Micro\Game\Proxx\Application\CommandHandler\PlaceBlackHolesHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\PlaceBlackHolesCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.install-cells:
    class: Micro\Game\Proxx\Application\CommandHandler\InstallCellsHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\InstallCellsCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.open-cell:
    class: Micro\Game\Proxx\Application\CommandHandler\OpenCellHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\OpenCellCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.mark-black-hole-on-cell:
    class: Micro\Game\Proxx\Application\CommandHandler\MarkBlackHoleOnCellHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\MarkBlackHoleOnCellCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.unmark-black-hole-on-cell:
    class: Micro\Game\Proxx\Application\CommandHandler\UnmarkBlackHoleOnCellHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\UnmarkBlackHoleOnCellCommand,
        bus: command.game.proxx
      }

  game.proxx.application.command_handler.board.process-game:
    class: Micro\Game\Proxx\Application\CommandHandler\ProcessGameHandler
    arguments:
      - '@game.proxx.infrastructure.repository.entity'
    tags:
      - {
        name: tactician.handler,
        command: Micro\Game\Proxx\Domain\Command\ProcessGameCommand,
        bus: command.game.proxx
      }
