services:
  _defaults:
    public: true

  # Factories
  game.proxx.domain.factory.command:
    class: Micro\Game\Proxx\Domain\Factory\CommandFactory

  game.proxx.domain.factory.value-object:
    class: Micro\Game\Proxx\Domain\Factory\ValueObjectFactory

  game.proxx.domain.factory.entity:
    class: Micro\Game\Proxx\Domain\Factory\EntityFactory
